### PR TITLE
Update workflows & enable Syntax API Code Gen tests

### LINKED ISSUE #5: Enable disabled syntaxApiCalls tests
**Description:**
$subject

Enable these tests once slp5 is published

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

### PR DESCRIPTION
**Pull request by SumayyaZiyad**
Fixes #5

### CODE REVIEW

**Comment by SumayyaZiyad** [comment]
@nadeeshaan @kdsuneraavinash Updated the workflow with the latest released pack. Please approve.

**Review by kdsuneraavinash — APPROVED** [review]

**Comment by kdsuneraavinash** [comment]
Is there a way to automatically pull the most recent build?

**Comment by nadeeshaan** [comment]
@kdsuneraavinash @SumayyaZiyad Shall we have a look at the following approach?
https://github.com/ballerina-platform/plugin-vscode/blob/master/.github/workflows/run-tests-windows.yml

**Comment by SumayyaZiyad** [comment]
> @kdsuneraavinash @SumayyaZiyad Shall we have a look at the following approach?
> https://github.com/ballerina-platform/plugin-vscode/blob/master/.github/workflows/run-tests-windows.yml

IINM, this approach is possible only for a manual workflow right? If required, we could do the same and manually trigger the workflow for every PR sent. And keep this current workflow also as a backup.

**Comment by nadeeshaan** [comment]
> > @kdsuneraavinash @SumayyaZiyad Shall we have a look at the following approach?
> > https://github.com/ballerina-platform/plugin-vscode/blob/master/.github/workflows/run-tests-windows.yml
> 
> IINM, this approach is possible only for a manual workflow right? If required, we could do the same and manually trigger the workflow for every PR sent. And keep this current workflow also as a backup.

We have done the same for ballerina plugin as well. so shall we follow that? And yes there is a certain manual part as I understood

**Comment by SumayyaZiyad** [comment]
> > > @kdsuneraavinash @SumayyaZiyad Shall we have a look at the following approach?
> > > https://github.com/ballerina-platform/plugin-vscode/blob/master/.github/workflows/run-tests-windows.yml
> > 
> > 
> > IINM, this approach is possible only for a manual workflow right? If required, we could do the same and manually trigger the workflow for every PR sent. And keep this current workflow also as a backup.
> 
> We have done the same for ballerina plugin as well. so shall we follow that? And yes there is a certain manual part as I understood

+1. Will include a separate manual workflow also with the same approach and update the PR.

**Comment by SumayyaZiyad** [comment]
@nadeeshaan @kdsuneraavinash the PR has been updated with the workflow changes as discussed.

**Review by nadeeshaan — APPROVED** [review]

**Pull request merged**
